
package com.cx.client.client01;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "WeatherServiceImpl", targetNamespace = "http://impl.Service.web.cx.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface WeatherServiceImpl {


    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "queryWeatherByCityName", targetNamespace = "http://impl.Service.web.cx.com/", className = "com.cx.client.client01.QueryWeatherByCityName")
    @ResponseWrapper(localName = "queryWeatherByCityNameResponse", targetNamespace = "http://impl.Service.web.cx.com/", className = "com.cx.client.client01.QueryWeatherByCityNameResponse")
    @Action(input = "http://impl.Service.web.cx.com/WeatherServiceImpl/queryWeatherByCityNameRequest", output = "http://impl.Service.web.cx.com/WeatherServiceImpl/queryWeatherByCityNameResponse")
    public String queryWeatherByCityName(
            @WebParam(name = "arg0", targetNamespace = "")
                    String arg0);

}
